apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: orders-service
  ports:
    - port: {{ .Values.ordersService.port }}
      targetPort: {{ .Values.ordersService.port }}
  type: ClusterIP