apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: {{ .Values.paymentsService.port }}
  type: ClusterIP