apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.usersPostgres.storage }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.usersPostgres.image }}
          ports:
            - containerPort: {{ .Values.usersPostgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.usersPostgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.usersPostgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.usersPostgres.db | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: users-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: users-postgres
spec:
  selector:
    app: users-postgres
  ports:
    - port: 5432
      targetPort: 5432