namespace:
  create: false

registry: k3d-finlab-registry:5000

backend:
  image: finlab/backend
  tag: "latest"
  replicas: 2
  port: 3000
  env:
    PORT: "3000"
    DB_MODE: "postgres"
    DATABASE_URL: ""   # optional override (if set, DB_* vars are ignored)
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_USER: "finlab"
    DB_PASSWORD: "finlab"
    DB_NAME: "finlab"
    ORDERS_SERVICE_URL: "http://orders-service:3000"
    PAYMENTS_SERVICE_URL: "http://payments-service:3002"
    USERS_SERVICE_URL: "http://users-service:3001"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

frontend:
  image: finlab/frontend
  tag: "latest"
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  user: finlab
  password: finlab
  db: finlab
  port: 5432
  storage: 1Gi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

usersService:
  image: finlab/users-service
  tag: "latest"
  replicas: 1
  port: 3001
  env:
    PORT: "3001"
    DB_HOST: "users-postgres"
    DB_PORT: "5432"
    DB_USER: "finlab"
    DB_PASSWORD: "finlab"
    DB_NAME: "finlab"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

usersPostgres:
  enabled: true
  image: postgres:15
  user: finlab
  password: finlab
  db: finlab
  port: 5432
  storage: 1Gi

ordersService:
  image: finlab/orders-service
  tag: "latest"
  replicas: 1
  port: 3000
  env:
    PORT: "3000"
    DB_HOST: "orders-postgres"
    DB_PORT: "5432"
    DB_USER: "finlab"
    DB_PASSWORD: "finlab"
    DB_NAME: "orders"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ordersPostgres:
  enabled: true
  image: postgres:15
  user: finlab
  password: finlab
  db: orders
  port: 5432
  storage: 1Gi
   
  
paymentsService:
  image: finlab/payments-service
  tag: "latest"
  replicas: 1
  port: 3002
  env:
    PORT: "3002"
    DB_HOST: "payments-postgres"
    DB_PORT: "5432"
    DB_USER: "finlab"
    DB_PASSWORD: "finlab"
    DB_NAME: "payments"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

paymentsPostgres:
  enabled: true
  image: postgres:15
  user: finlab
  password: finlab
  db: payments
  port: 5432
  storage: 1Gi